// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
	/**
	 *  Writes text at the cursor position using the clipboard sandwich technique
	 *
	 *  This method preserves the user's existing clipboard content by:
	 *  1. Saving the current clipboard content
	 *  2. Writing the new text to clipboard
	 *  3. Simulating a paste operation (Cmd+V on macOS, Ctrl+V elsewhere)
	 *  4. Restoring the original clipboard content
	 *
	 *  This approach is faster than typing character-by-character and preserves
	 *  the user's clipboard, making it ideal for inserting transcribed text.
	 */
	writeText: (text: string) =>
		typedError<null, string>(__TAURI_INVOKE('write_text', { text })),
	/**
	 *  Simulates pressing the Enter/Return key
	 *
	 *  This is useful for automatically submitting text in chat applications
	 *  after transcription has been pasted.
	 */
	simulateEnterKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_enter_keystroke')),
	/**
	 *  Simulates pressing the copy shortcut (Cmd+C on macOS, Ctrl+C elsewhere)
	 *
	 *  This copies the active selection in the foreground app to the clipboard. The
	 *  frontend pairs it with a clipboard save/read/restore to capture the user's
	 *  selection without clobbering their clipboard (see the text service's
	 *  `captureSelection`).
	 */
	simulateCopyKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_copy_keystroke')),
	getCurrentRecordingId: () =>
		typedError<string | null, string>(
			__TAURI_INVOKE('get_current_recording_id'),
		),
	enumerateRecordingDevices: () =>
		typedError<string[], string>(__TAURI_INVOKE('enumerate_recording_devices')),
	initRecordingSession: (
		deviceIdentifier: string,
		recordingId: string,
		sampleRate: number | null,
	) =>
		typedError<null, string>(
			__TAURI_INVOKE('init_recording_session', {
				deviceIdentifier,
				recordingId,
				sampleRate,
			}),
		),
	closeRecordingSession: () =>
		typedError<null, string>(__TAURI_INVOKE('close_recording_session')),
	startRecording: () =>
		typedError<null, string>(__TAURI_INVOKE('start_recording')),
	/**
	 *  Stop the recorder, write the canonical WAV artifact to
	 *  `<appDataDir>/recordings/{id}.wav`, return the small JSON handle.
	 *
	 *  JS never sees raw PCM samples on the wire: later operations look the
	 *  file up by id (`transcribe_recording`, `encode_recording_for_upload`,
	 *  and `delete_recording_artifacts`).
	 */
	stopRecording: () =>
		typedError<RecordingArtifact, string>(__TAURI_INVOKE('stop_recording')),
	cancelRecording: () =>
		typedError<null, string>(__TAURI_INVOKE('cancel_recording')),
	/**
	 *  Delete recording artifacts by id.
	 *
	 *  This is intentionally id-based instead of path-based. The recorder
	 *  artifact module owns which files under the recordings directory are blobs,
	 *  so TypeScript callers cannot accidentally delete markdown sidecars or
	 *  arbitrary files. Missing artifacts are ignored to keep cleanup retryable.
	 */
	deleteRecordingArtifacts: (recordingIds: string[]) =>
		typedError<number, string>(
			__TAURI_INVOKE('delete_recording_artifacts', { recordingIds }),
		),
	/**
	 *  Delete every recording artifact while preserving markdown sidecars.
	 *
	 *  Used by the blob store's `clear()` path. The Rust layer owns the directory
	 *  scan because it has the same artifact matching rule used by targeted
	 *  deletion and transcription lookup.
	 */
	clearRecordingArtifacts: () =>
		typedError<number, string>(__TAURI_INVOKE('clear_recording_artifacts')),
	/**
	 *  Canonical transcribe-by-id path. Resolves the audio file under
	 *  `<appDataDir>/recordings/{recordingId}.*` (cpal-written WAV,
	 *  navigator-saved webm/opus/mp4, etc.), decodes, runs inference using
	 *  the ambient configuration pushed via `set_transcription_config`.
	 *
	 *  Returns `NoConfig` if the FE has not pushed a config yet.
	 */
	transcribeRecording: (recordingId: string) =>
		typedError<string, TranscriptionError>(
			__TAURI_INVOKE('transcribe_recording', { recordingId }),
		),
	/**
	 *  Open macOS Accessibility settings.
	 *
	 *  This is intentionally a fixed command instead of a general command
	 *  runner. The app only needs this one OS handoff, so the frontend should
	 *  not receive shell or process execution privileges.
	 */
	openAccessibilitySettings: () =>
		typedError<null, string>(__TAURI_INVOKE('open_accessibility_settings')),
	/**
	 *  Writes markdown files to disk atomically using a temporary file plus persist.
	 *  Validates all filenames upfront. No files are written if any name is invalid.
	 *
	 *  # Arguments
	 *  * `directory` - Absolute path to the output directory
	 *  * `files` - Array of `{ filename, content }` pairs to write
	 *
	 *  # Returns
	 *  * `Ok(())` - All files written successfully
	 *  * `Err(String)` - Error if any write fails (earlier files may already be on disk)
	 */
	writeMarkdownFiles: (directory: string, files: MarkdownFile[]) =>
		typedError<null, string>(
			__TAURI_INVOKE('write_markdown_files', { directory, files }),
		),
	/**
	 *  Push the ambient transcription configuration. Replaces the per-call
	 *  `config` argument that `transcribe_recording` used to take. The FE
	 *  invokes this once at startup and on every subsequent change to
	 *  settings, model selection, language, prompt, or unload policy.
	 *
	 *  Drift in `(engine, model_name)` triggers a background preload so the
	 *  next `transcribe_recording` call does not pay cold-start latency.
	 *  Other field changes take effect on the next transcription with no
	 *  reload.
	 */
	setTranscriptionConfig: (config: TranscriptionConfig) =>
		__TAURI_INVOKE<void>('set_transcription_config', { config }),
	/**
	 *  Snapshot the current model state. Used by late-mounted observers (a
	 *  second window, the settings panel re-opening, etc.) to catch up to
	 *  the current lifecycle state without waiting for the next event on
	 *  `transcription://model-state`.
	 *
	 *  Reads a lock-free status field plus the ambient config; never touches
	 *  the cache mutex, so it returns immediately even mid-inference.
	 */
	getTranscriptionState: () =>
		__TAURI_INVOKE<LocalModelState>('get_transcription_state'),
	/**
	 *  Download `url` to `file_path`, cancelable via `cancel_download(download_id)`.
	 *
	 *  Runs the transfer in a `tokio` task whose `AbortHandle` is registered under
	 *  `download_id`. A cancel aborts the task at its next await point, which
	 *  surfaces here as an `Err`; the frontend, which knows it requested the
	 *  cancel, treats that error as a clean stop.
	 */
	downloadFile: (
		downloadId: string,
		url: string,
		filePath: string,
		onProgress: Channel<DownloadProgress>,
	) =>
		typedError<null, string>(
			__TAURI_INVOKE('download_file', {
				downloadId,
				url,
				filePath,
				onProgress,
			}),
		),
	/**
	 *  Abort the in-flight download registered under `download_id`, if any. The
	 *  matching `download_file` call then resolves with an `Err`. A no-op when
	 *  nothing is downloading under that id (already finished, or cancelled between
	 *  files), so it is always safe to call.
	 */
	cancelDownload: (downloadId: string) =>
		__TAURI_INVOKE<void>('cancel_download', { downloadId }),
	pauseActiveMedia: () =>
		typedError<PauseActiveMediaOutcome, string>(
			__TAURI_INVOKE('pause_active_media'),
		),
	resumeMedia: (players: MediaPlayer[]) =>
		typedError<MediaControlFailure[], string>(
			__TAURI_INVOKE('resume_media', { players }),
		),
	/**
	 *  Replace the full set of registered global shortcuts. The FE computes the
	 *  complete list from device-config and pushes it on startup and on every
	 *  change; the listener swaps its binding set atomically. Replace-all (not
	 *  per-command register/unregister) keeps the FE the single source of truth for
	 *  what is bound, with no add/remove bookkeeping to drift.
	 */
	setKeyboardShortcuts: (bindings: CommandBinding[]) =>
		__TAURI_INVOKE<void>('set_keyboard_shortcuts', { bindings }),
	/**
	 *  Enter or leave binding-capture mode for the settings recorder. While
	 *  capturing, the listener emits the held combo as a `ShortcutCaptureEvent`
	 *  (which the recorder accumulates) instead of firing command triggers, so the
	 *  user can record Fn and physical-key bindings the webview cannot see.
	 */
	setKeyboardCapturing: (capturing: boolean) =>
		__TAURI_INVOKE<void>('set_keyboard_capturing', { capturing }),
	/**
	 *  Start the rdev listener if it is not already running, returning whether it
	 *  started (or why not). The FE calls this once it knows global shortcuts are
	 *  allowed: on macOS after Accessibility is granted, on other desktops at
	 *  launch. Idempotent, so re-checks on focus are safe.
	 */
	startKeyboardListener: () =>
		__TAURI_INVOKE<ListenerStart>('start_keyboard_listener'),
};

/** Events */
export const events = {
	modelStateEvent: makeEvent<ModelStateEvent>('model-state-event'),
	shortcutCaptureEvent: makeEvent<ShortcutCaptureEvent>(
		'shortcut-capture-event',
	),
	shortcutTriggerEvent: makeEvent<ShortcutTriggerEvent>(
		'shortcut-trigger-event',
	),
};

/* Types */
/**
 *  One command's binding, as sent from the FE registrar. `command_id` is the
 *  id the trigger event is emitted under; the FE filters by that command's `on`
 *  array and dispatches the callback.
 */
export type CommandBinding = {
	commandId: string;
	binding: KeyBinding;
};

/**  Whole-file download progress: bytes received so far and the total to expect. */
export type DownloadProgress = {
	/**
	 *  Bytes received so far. `f64` because specta forbids exporting 64-bit
	 *  ints to TypeScript; model sizes are far below `f64`'s 2^53 exact-integer
	 *  ceiling, so no precision is lost.
	 */
	bytesReceived: number | null;
	/**
	 *  Total bytes from the response `content-length`, or 0 when the server
	 *  omits it. The frontend falls back to the catalog size in that case.
	 */
	totalBytes: number | null;
};

/**
 *  Local transcription engine. Wire tags match the frontend
 *  `transcription.service` enum (`whispercpp` / `parakeet` / `moonshine`).
 */
export type Engine = 'whispercpp' | 'parakeet' | 'moonshine';

/**
 *  A non-modifier key, named by physical position (Wave 1 Lock: desktop binds
 *  in physical-key space, not produced-character space). Variant names mirror
 *  rdev's `Key` for the keys we support so the rdev mapping is near 1:1, but
 *  this is our own stable enum: the persisted binding format must not depend on
 *  rdev's enum names. Keys outside this set are not bindable (`rdev_map` returns
 *  `None`), which keeps this a pure string union on the TypeScript side.
 */
export type Key =
	| 'keyA'
	| 'keyB'
	| 'keyC'
	| 'keyD'
	| 'keyE'
	| 'keyF'
	| 'keyG'
	| 'keyH'
	| 'keyI'
	| 'keyJ'
	| 'keyK'
	| 'keyL'
	| 'keyM'
	| 'keyN'
	| 'keyO'
	| 'keyP'
	| 'keyQ'
	| 'keyR'
	| 'keyS'
	| 'keyT'
	| 'keyU'
	| 'keyV'
	| 'keyW'
	| 'keyX'
	| 'keyY'
	| 'keyZ'
	| 'num0'
	| 'num1'
	| 'num2'
	| 'num3'
	| 'num4'
	| 'num5'
	| 'num6'
	| 'num7'
	| 'num8'
	| 'num9'
	| 'f1'
	| 'f2'
	| 'f3'
	| 'f4'
	| 'f5'
	| 'f6'
	| 'f7'
	| 'f8'
	| 'f9'
	| 'f10'
	| 'f11'
	| 'f12'
	| 'f13'
	| 'f14'
	| 'f15'
	| 'f16'
	| 'f17'
	| 'f18'
	| 'f19'
	| 'f20'
	| 'f21'
	| 'f22'
	| 'f23'
	| 'f24'
	| 'space'
	| 'return'
	| 'tab'
	| 'escape'
	| 'backspace'
	| 'delete'
	| 'insert'
	| 'upArrow'
	| 'downArrow'
	| 'leftArrow'
	| 'rightArrow'
	| 'home'
	| 'end'
	| 'pageUp'
	| 'pageDown'
	| 'minus'
	| 'equal'
	| 'leftBracket'
	| 'rightBracket'
	| 'semiColon'
	| 'quote'
	| 'backQuote'
	| 'backSlash'
	| 'comma'
	| 'dot'
	| 'slash';

/**
 *  A desktop global binding. It fires when its modifiers and keys are held
 *  exactly (see `Matcher`), matching the existing `arraysMatch` semantics of
 *  `local-shortcut-manager` and the plugin's exact-modifier behavior. An empty
 *  `keys` with non-empty `modifiers` is a modifier-only hold (for example hold
 *  Meta); empty `modifiers` with one key is a bare single-key push-to-talk.
 *  Both were impossible with the plugin.
 */
export type KeyBinding = {
	modifiers: Modifier[];
	keys: Key[];
};

/**
 *  Outcome of a `start` request, so the FE can tell the user when global
 *  shortcuts are unavailable instead of relying on a Rust log nobody sees.
 */
export type ListenerStart =
	/**  A listener thread was spawned. */
	| 'started'
	/**  A listener thread is already running; this call was a no-op. */
	| 'alreadyRunning'
	/**  Linux Wayland: rdev's tap never receives events, so nothing was spawned. */
	| 'waylandUnsupported';

/**
 *  Snapshot of everything observable about the resident model. Every event
 *  carries a full snapshot rather than a delta because `AppHandle::emit`
 *  does not replay to future windows: a window opened mid-load reads the
 *  current snapshot via `get_transcription_state` and then catches up via
 *  the next event.
 */
export type LocalModelState = {
	engine: Engine | null;
	/**
	 *  Entry name inside the engine's models directory, mirroring
	 *  `TranscriptionConfig::model_name`.
	 */
	modelName: string | null;
	status: ModelStatus;
};

export type MarkdownFile = {
	filename: string;
	content: string;
};

export type MediaControlFailure = {
	player: MediaPlayer;
	message: string;
	permissionDenied: boolean;
};

export type MediaPlayer = 'music' | 'spotify';

/**
 *  Single event type for everything observable about the model lifecycle.
 *  `tag = "kind"` matches `ModelStatus` and `UnloadReason` so the FE pattern
 *  is uniform: `switch (event.kind)`.
 *
 *  Registered as a `tauri_specta::Event`, so the Rust emitter
 *  (`event.emit(&app)`) and the generated FE binding (`events.modelStateEvent`)
 *  share one generated topic name instead of a hand-mirrored string.
 */
export type ModelStateEvent =
	| { kind: 'loading_started'; state: LocalModelState }
	| { kind: 'loading_completed'; state: LocalModelState; elapsedMs: number }
	| { kind: 'loading_failed'; state: LocalModelState; error: string }
	| { kind: 'inference_started'; state: LocalModelState }
	| { kind: 'inference_completed'; state: LocalModelState; elapsedMs: number }
	| { kind: 'inference_failed'; state: LocalModelState; error: string }
	| { kind: 'unloaded'; state: LocalModelState; reason: UnloadReason }
	| { kind: 'selection_changed'; state: LocalModelState };

/**
 *  Lifecycle state of the resident model. Owned by an `Arc<RwLock<...>>`
 *  inside `ModelManager` so `snapshot()` can read it without touching the
 *  cache mutex (which is held across long-running inference).
 */
export type ModelStatus =
	/**
	 *  No model resident and none loading. Initial state, and reached after
	 *  `Unloaded`.
	 */
	| { kind: 'idle' }
	/**  `with_engine` is currently inside the `load(&model_path)` call. */
	| { kind: 'loading' }
	/**  A model is resident and not currently in use. */
	| { kind: 'ready' }
	/**
	 *  `with_engine` is currently inside the user closure (transcribe call).
	 *  The cache lock is held; `snapshot()` reports this without contending.
	 */
	| { kind: 'inferring' }
	/**
	 *  The last attempt to load or transcribe failed. Inference failures may
	 *  leave the engine resident so a later transcription can reuse it.
	 */
	| { kind: 'error'; message: string };

/**
 *  A logical modifier. Left and right are collapsed in v1 (ControlLeft and
 *  ControlRight both become `Ctrl`); the Wayland and left/right gaps are
 *  documented refusals in the spec. `Fn` is the capability the Tauri
 *  global-shortcut plugin could never express.
 */
export type Modifier = 'ctrl' | 'alt' | 'shift' | 'meta' | 'fn';

export type PauseActiveMediaOutcome = {
	paused: MediaPlayer[];
	failures: MediaControlFailure[];
};

/**
 *  Serializable handle returned to the JS side. The id is the lookup key
 *  for every later operation; the rest is metadata the UI needs without
 *  having to read the file (duration for analytics, byteLength for artifact
 *  diagnostics, mimeType for the player).
 *
 *  `mime_type` is `String` rather than `&'static str` so specta's TS
 *  generator sees a stable serializable shape. The runtime cost is one short
 *  allocation per artifact write.
 *
 *  `duration_ms` and `byte_length` use `#[specta(type = Number<u64>)]`
 *  to opt out of specta's bigint guard: both stay well under
 *  `Number.MAX_SAFE_INTEGER` (2^53) for any plausible recording
 *  (duration in ms maxes at ~285,000 years; byte length is bounded by
 *  the filesystem).
 */
export type RecordingArtifact = {
	id: string;
	durationMs: number;
	byteLength: number;
	mimeType: string;
};

/**
 *  Streamed on every change of the currently-held combo while the settings
 *  recorder is capturing a new binding. A dedicated event type (rather than
 *  emitting a bare `KeyBinding`) so capture is a `tauri_specta::Event` like the
 *  trigger, with a generated topic and FE binding. Recording goes through rdev,
 *  not the webview, because only rdev sees the Fn key and physical-key
 *  positions, so the captured binding is exactly what the matcher will later
 *  match. The FE accumulates these snapshots and commits when all keys release.
 */
export type ShortcutCaptureEvent = {
	binding: KeyBinding;
};

/**
 *  Emitted on every binding transition. `command_id` is the id the binding was
 *  registered under; the FE filters by that command's `on` array and dispatches
 *  the callback. Rust stays command-agnostic: it knows the id and the edge, not
 *  which states a given command cares about.
 *
 *  A `tauri_specta::Event`, so the listener emits it with
 *  `trigger.emit_to(app, MAIN_WINDOW)` (targeting the main webview, not the
 *  overlay) and the FE listens through the generated `events.shortcutTriggerEvent`.
 */
export type ShortcutTriggerEvent = {
	commandId: string;
	state: TriggerState;
};

/**
 *  Ambient configuration the frontend pushes once per change. The Rust side
 *  reads this on every `transcribe_recording` call instead of receiving
 *  a per-call payload. The model loads lazily on the next transcription, so a
 *  changed `(engine, model_name)` is picked up then; drift in other fields
 *  takes effect on the next transcription with no reload.
 */
export type TranscriptionConfig = {
	engine: Engine;
	/**
	 *  Entry name inside the engine's models directory (a single file or
	 *  directory name, never a path). `ModelManager` resolves it under
	 *  `{app_data}/models/{engine}/` at load time, so a path never exists
	 *  as data anywhere in the system.
	 */
	modelName: string;
	language?: string | null;
	initialPrompt?: string | null;
	unloadPolicy: UnloadPolicy;
};

export type TranscriptionError =
	| { name: 'AudioReadError'; message: string }
	| { name: 'GpuError'; message: string }
	| { name: 'ModelLoadError'; message: string }
	| { name: 'TranscriptionError'; message: string }
	/**
	 *  `transcribe_recording` was called before `set_transcription_config`
	 *  pushed an ambient config. The FE should disable the transcribe button
	 *  until `localModel.state.engine !== null` to avoid this.
	 */
	| { name: 'NoConfig'; message: string }
	/**
	 *  The ambient config holds a value that cannot be dispatched (e.g. a
	 *  Moonshine model path that does not match `moonshine-{variant}-{lang}`).
	 */
	| { name: 'ConfigError'; message: string };

/**
 *  Whether a binding just became fully held (`Pressed`) or stopped being fully
 *  held (`Released`). The variant names serialize verbatim to `"Pressed"` /
 *  `"Released"`, which is exactly the `ShortcutEventState` the Tauri
 *  global-shortcut plugin used to deliver, so the command layer (`commands.ts`)
 *  is unchanged: only the producer of these strings changes.
 */
export type TriggerState = 'Pressed' | 'Released';

/**
 *  How long after the last transcription the resident model should be
 *  dropped. Mirrors the frontend `transcription.localModelUnloadPolicy`
 *  device setting; serde tags below match its wire format exactly so the
 *  FE value pushes straight through.
 *
 *  `Immediately` is enforced synchronously at the end of each transcription;
 *  timed variants are enforced by the background idle watcher.
 */
export type UnloadPolicy =
	| 'never'
	| 'immediately'
	| 'after_5_minutes'
	| 'after_30_minutes';

/**
 *  Reason the resident model was dropped. Folded into a single event variant
 *  (`ModelStateEvent::Unloaded`) rather than fanned out into per-reason
 *  variants so the FE has one branch to handle.
 */
export type UnloadReason =
	/**
	 *  Synchronous eviction after a transcription completed under the
	 *  `Immediately` unload policy.
	 */
	| { kind: 'immediate' }
	/**
	 *  Background idle watcher dropped the model after the configured timeout
	 *  elapsed without activity.
	 */
	| { kind: 'idle'; idleSecs: number }
	/**
	 *  User selected a different model in settings; the old one was dropped
	 *  before the new one preloads.
	 */
	| { kind: 'config_changed' };

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}

type EventEmit<T> = [T] extends [null]
	? () => Promise<void>
	: (payload: T) => Promise<void>;

function makeEvent<T>(
	name: string,
	serialize?: (payload: T) => unknown,
	deserialize?: (payload: any) => T,
) {
	const mapEvent =
		(cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
			cb({
				...event,
				payload: deserialize ? deserialize(event.payload) : event.payload,
			});
	const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

	const base = {
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			__TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	};

	const fn = (
		target:
			| import('@tauri-apps/api/webview').Webview
			| import('@tauri-apps/api/window').Window,
	) => ({
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	});

	return Object.assign(fn, base);
}
