// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Writes text at the cursor position using the clipboard sandwich technique
	 * 
	 *  This method preserves the user's existing clipboard content by:
	 *  1. Saving the current clipboard content
	 *  2. Writing the new text to clipboard
	 *  3. Simulating a paste operation (Cmd+V on macOS, Ctrl+V elsewhere)
	 *  4. Restoring the original clipboard content
	 * 
	 *  This approach is faster than typing character-by-character and preserves
	 *  the user's clipboard, making it ideal for inserting transcribed text.
	 */
	writeText: (text: string) => typedError<null, string>(__TAURI_INVOKE("write_text", { text })),
	/**
	 *  Simulates pressing the Enter/Return key
	 * 
	 *  This is useful for automatically submitting text in chat applications
	 *  after transcription has been pasted.
	 */
	simulateEnterKeystroke: () => typedError<null, string>(__TAURI_INVOKE("simulate_enter_keystroke")),
	getCurrentRecordingId: () => typedError<string | null, string>(__TAURI_INVOKE("get_current_recording_id")),
	enumerateRecordingDevices: () => typedError<string[], string>(__TAURI_INVOKE("enumerate_recording_devices")),
	initRecordingSession: (deviceIdentifier: string, recordingId: string, sampleRate: number | null) => typedError<null, string>(__TAURI_INVOKE("init_recording_session", { deviceIdentifier, recordingId, sampleRate })),
	closeRecordingSession: () => typedError<null, string>(__TAURI_INVOKE("close_recording_session")),
	startRecording: () => typedError<null, string>(__TAURI_INVOKE("start_recording")),
	/**
	 *  Stop the recorder, write the canonical WAV artifact to
	 *  `<appDataDir>/recordings/{id}.wav`, return the small JSON handle.
	 * 
	 *  JS never sees raw PCM samples on the wire: later operations look the
	 *  file up by id (`transcribe_recording`, `encode_recording_for_upload`,
	 *  `delete_recording`).
	 */
	stopRecording: () => typedError<RecordingArtifact, string>(__TAURI_INVOKE("stop_recording")),
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
	/**
	 *  Delete an artifact by id. Idempotent: a missing file is not an error
	 *  so the JS side can call this without first checking existence.
	 */
	deleteRecording: (recordingId: string) => typedError<null, string>(__TAURI_INVOKE("delete_recording", { recordingId })),
	/**
	 *  Canonical transcribe-by-id path. Resolves the audio file under
	 *  `<appDataDir>/recordings/{recordingId}.*` (cpal-written WAV,
	 *  navigator-saved webm/opus/mp4, etc.), decodes, runs inference using
	 *  the ambient configuration pushed via `set_transcription_config`.
	 * 
	 *  Returns `NoConfig` if the FE has not pushed a config yet.
	 */
	transcribeRecording: (recordingId: string) => typedError<string, TranscriptionError>(__TAURI_INVOKE("transcribe_recording", { recordingId })),
	/**
	 *  Open macOS Accessibility settings.
	 * 
	 *  This is intentionally a fixed command instead of a general command
	 *  runner. The app only needs this one OS handoff, so the frontend should
	 *  not receive shell or process execution privileges.
	 */
	openAccessibilitySettings: () => typedError<null, string>(__TAURI_INVOKE("open_accessibility_settings")),
	/**
	 *  Deletes files inside a directory by filename.
	 *  Validates filenames are single path components (no traversal).
	 *  Uses Rayon for parallel deletion. Silently skips missing files.
	 * 
	 *  # Arguments
	 *  * `filenames` - Array of leaf filenames to delete
	 */
	deleteRecordingFiles: (filenames: string[]) => typedError<number, string>(__TAURI_INVOKE("delete_recording_files", { filenames })),
	/**
	 *  Writes markdown files to disk atomically using a temporary file plus persist.
	 *  Validates all filenames before writing so invalid names do not touch disk.
	 * 
	 *  # Arguments
	 *  * `files` - Array of `{ filename, content }` pairs to write
	 * 
	 *  # Returns
	 *  * `Ok(())` - All files written successfully
	 *  * `Err(String)` - Error if any write fails (earlier files may already be on disk)
	 */
	writeRecordingMarkdownFiles: (files: MarkdownFile[]) => typedError<null, string>(__TAURI_INVOKE("write_recording_markdown_files", { files })),
	/**
	 *  Push the ambient transcription configuration. Replaces the per-call
	 *  `config` argument that `transcribe_recording` used to take. The FE
	 *  invokes this once at startup and on every subsequent change to
	 *  settings, model selection, language, prompt, or unload policy.
	 * 
	 *  Drift in `(engine, modelPath)` triggers a background preload so the
	 *  next `transcribe_recording` call does not pay cold-start latency.
	 *  Other field changes take effect on the next transcription with no
	 *  reload.
	 */
	setTranscriptionConfig: (config: TranscriptionConfig) => __TAURI_INVOKE<void>("set_transcription_config", { config }),
	/**
	 *  Snapshot the current model state. Used by late-mounted observers (a
	 *  second window, the settings panel re-opening, etc.) to catch up to
	 *  the current lifecycle state without waiting for the next event on
	 *  `transcription://model-state`.
	 * 
	 *  Reads a lock-free status field plus the ambient config; never touches
	 *  the cache mutex, so it returns immediately even mid-inference.
	 */
	getTranscriptionState: () => __TAURI_INVOKE<LocalModelState>("get_transcription_state"),
};

/** Events */
export const events = {
	transcriptionModelState: makeEvent<ModelStateEvent>("transcription://model-state"),
};

/* Types */
/**
 *  Local transcription engine. Wire tags match the frontend
 *  `transcription.service` enum (`whispercpp` / `parakeet` / `moonshine`).
 */
export type Engine = "whispercpp" | "parakeet" | "moonshine";

/**
 *  Snapshot of everything observable about the resident model. Every event
 *  carries a full snapshot rather than a delta because `AppHandle::emit`
 *  does not replay to future windows: a window opened mid-load reads the
 *  current snapshot via `get_transcription_state` and then catches up via
 *  the next event.
 */
export type LocalModelState = {
	engine: Engine | null,
	modelPath: string | null,
	status: ModelStatus,
};

export type MarkdownFile = {
	filename: string,
	content: string,
};

/**
 *  Single event type for everything observable about the model lifecycle.
 *  `tag = "kind"` matches `ModelStatus` and `UnloadReason` so the FE pattern
 *  is uniform: `switch (event.kind)`.
 * 
 *  `tauri_specta::Event` + `event_name = "..."` keys the TS export at the
 *  custom channel name. Without the explicit name, the derive kebab-cases
 *  the type ident (`model-state-event`) which would break the existing FE
 *  listener. `collect_events![ModelStateEvent]` in `lib.rs` registers the
 *  type so the regen surface picks it up.
 */
export type ModelStateEvent = { kind: "loading_started"; state: LocalModelState } | { kind: "loading_completed"; state: LocalModelState; elapsed_ms: number } | { kind: "loading_failed"; state: LocalModelState; error: string } | { kind: "unloaded"; state: LocalModelState; reason: UnloadReason } | { kind: "selection_changed"; state: LocalModelState };

/**
 *  Lifecycle state of the resident model. Owned by an `Arc<RwLock<...>>`
 *  inside `ModelManager` so `snapshot()` can read it without touching the
 *  cache mutex (which is held across long-running inference).
 */
export type ModelStatus = 
/**
 *  No model resident and none loading. Initial state, and reached after
 *  `Unloaded`.
 */
{ kind: "idle" } | 
/**  `with_engine` is currently inside the `load(&model_path)` call. */
{ kind: "loading" } | 
/**  A model is resident and not currently in use. */
{ kind: "ready" } | 
/**
 *  `with_engine` is currently inside the user closure (transcribe call).
 *  The cache lock is held; `snapshot()` reports this without contending.
 */
{ kind: "inferring" } | 
/**  The last attempt to load or transcribe failed. The cache is empty. */
{ kind: "error"; message: string };

/**
 *  Serializable handle returned to the JS side. The id is the lookup key
 *  for every later operation; the rest is metadata the UI needs without
 *  having to read the file (duration for analytics, byteLength for upload
 *  size, mimeType for the player).
 * 
 *  `mime_type` is `String` rather than `&'static str` so specta's TS
 *  generator sees a stable serializable shape (and so future producers,
 *  e.g. navigator-saved webm artifacts after the next collapse, can set
 *  it to a non-static value). The runtime cost is one short allocation
 *  per artifact write.
 * 
 *  `duration_ms` and `byte_length` use `#[specta(type = Number<u64>)]`
 *  to opt out of specta's bigint guard: both stay well under
 *  `Number.MAX_SAFE_INTEGER` (2^53) for any plausible recording
 *  (duration in ms maxes at ~285,000 years; byte length is bounded by
 *  the filesystem).
 */
export type RecordingArtifact = {
	id: string,
	durationMs: number,
	byteLength: number,
	mimeType: string,
};

/**
 *  Ambient configuration the frontend pushes once per change. The Rust side
 *  reads this on every `transcribe_recording` call instead of receiving
 *  a per-call payload. Drift in `(engine, model_path)` triggers a preload;
 *  drift in other fields takes effect on the next transcription with no
 *  reload.
 */
export type TranscriptionConfig = {
	engine: Engine,
	modelPath: string,
	language?: string | null,
	initialPrompt?: string | null,
	unloadPolicy: UnloadPolicy,
};

export type TranscriptionError = { name: "AudioReadError"; message: string } | { name: "GpuError"; message: string } | { name: "ModelLoadError"; message: string } | { name: "TranscriptionError"; message: string } | 
/**
 *  `transcribe_recording` was called before `set_transcription_config`
 *  pushed an ambient config. The FE should disable the transcribe button
 *  until `localModel.state.engine !== null` to avoid this.
 */
{ name: "NoConfig"; message: string } | 
/**
 *  The ambient config holds a value that cannot be dispatched (e.g. a
 *  Moonshine model path that does not match `moonshine-{variant}-{lang}`).
 */
{ name: "ConfigError"; message: string };

/**
 *  How long after the last transcription the resident model should be
 *  dropped. Mirrors the frontend `transcription.localModelUnloadPolicy`
 *  device setting; serde tags below match its wire format exactly so the
 *  FE value pushes straight through.
 * 
 *  `Immediately` is enforced synchronously at the end of each transcription;
 *  timed variants are enforced by the background idle watcher.
 */
export type UnloadPolicy = "never" | "immediately" | "after_5_minutes" | "after_30_minutes";

/**
 *  Reason the resident model was dropped. Folded into a single event variant
 *  (`ModelStateEvent::Unloaded`) rather than fanned out into per-reason
 *  variants so the FE has one branch to handle.
 */
export type UnloadReason = 
/**
 *  Synchronous eviction after a transcription completed under the
 *  `Immediately` unload policy.
 */
{ kind: "immediate" } | 
/**
 *  Background idle watcher dropped the model after the configured timeout
 *  elapsed without activity.
 */
{ kind: "idle"; idle_secs: number } | 
/**
 *  User selected a different model in settings; the old one was dropped
 *  before the new one preloads.
 */
{ kind: "config_changed" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

