// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, type Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
	/**
	 *  Delivers text to the cursor, falling back to the clipboard when it cannot.
	 *
	 *  The reach is decided from the live Accessibility *capability* before the
	 *  keystroke, not from the keystroke's result. A `Broken` grant — one that still
	 *  reads as trusted via `AXIsProcessTrusted` but whose synthetic events the OS
	 *  drops — lets the paste return `Ok` while nothing lands, so observing the
	 *  result is unreliable.
	 *
	 *  The clipboard is the paste transport, and `keep_on_clipboard` is the caller's
	 *  statement of what the clipboard should hold *afterward*:
	 *
	 *  - `keep_on_clipboard == true` (clipboard output is on): the transcript is the
	 *    intended final clipboard state, so we write it, paste, and leave it. No
	 *    snapshot, no restore.
	 *  - `keep_on_clipboard == false` (clipboard output is off): we borrow the
	 *    clipboard. Snapshot what the user had, write the transcript (concealed on
	 *    macOS so clipboard-history managers skip it), paste, then restore the
	 *    snapshot — so `write_text` leaves the clipboard exactly as it found it. On
	 *    macOS the snapshot is full-fidelity native `NSPasteboard` save/restore (see
	 *    `clipboard.rs`), which fixes the silent loss of a non-text clipboard
	 *    (image, file); every other platform keeps the text-only plugin save/restore.
	 *
	 *  When we cannot paste, or the paste fails, the transcript is left on the
	 *  clipboard as the fallback (this wins over restoring the snapshot). The
	 *  transcript is independently saved to history either way, so a fallback is a
	 *  reduced reach, never data loss.
	 */
	writeText: (text: string, keepOnClipboard: boolean) =>
		typedError<WriteTextOutcome, string>(
			__TAURI_INVOKE('write_text', { text, keepOnClipboard }),
		),
	/**
	 *  Simulates pressing the Enter/Return key
	 *
	 *  This is useful for automatically submitting text in chat applications
	 *  after transcription has been pasted.
	 */
	simulateEnterKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_enter_keystroke')),
	/**
	 *  Simulates pressing the copy shortcut (Cmd+C on macOS, Ctrl+C elsewhere)
	 *
	 *  This copies the active selection in the foreground app to the clipboard. The
	 *  frontend pairs it with a clipboard save/read/restore to capture the user's
	 *  selection without clobbering their clipboard (see the text service's
	 *  `captureSelection`).
	 */
	simulateCopyKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_copy_keystroke')),
	getCurrentRecordingId: () =>
		typedError<string | null, RecorderError>(
			__TAURI_INVOKE('get_current_recording_id'),
		),
	enumerateRecordingDevices: () =>
		typedError<string[], RecorderError>(
			__TAURI_INVOKE('enumerate_recording_devices'),
		),
	initRecordingSession: (
		deviceIdentifier: string,
		recordingId: string,
		sampleRate: number | null,
	) =>
		typedError<null, RecorderError>(
			__TAURI_INVOKE('init_recording_session', {
				deviceIdentifier,
				recordingId,
				sampleRate,
			}),
		),
	closeRecordingSession: () =>
		typedError<null, RecorderError>(__TAURI_INVOKE('close_recording_session')),
	startRecording: () =>
		typedError<null, RecorderError>(__TAURI_INVOKE('start_recording')),
	/**
	 *  Stop the recorder, write the canonical WAV artifact to
	 *  `<appDataDir>/recordings/{id}.wav`, return the small JSON handle.
	 *
	 *  JS never sees raw PCM samples on the wire: later operations look the
	 *  file up by id (`transcribe_recording`, `encode_recording_for_upload`,
	 *  and `delete_recording_artifacts`).
	 */
	stopRecording: () =>
		typedError<RecordingArtifact, RecorderError>(
			__TAURI_INVOKE('stop_recording'),
		),
	cancelRecording: () =>
		typedError<null, RecorderError>(__TAURI_INVOKE('cancel_recording')),
	/**
	 *  Delete recording artifacts by id.
	 *
	 *  This is intentionally id-based instead of path-based. The recorder
	 *  artifact module owns which files under the recordings directory are blobs,
	 *  so TypeScript callers cannot accidentally delete markdown sidecars or
	 *  arbitrary files. Missing artifacts are ignored to keep cleanup retryable.
	 */
	deleteRecordingArtifacts: (recordingIds: string[]) =>
		typedError<number, RecorderError>(
			__TAURI_INVOKE('delete_recording_artifacts', { recordingIds }),
		),
	/**
	 *  Delete every recording artifact while preserving markdown sidecars.
	 *
	 *  Used by the blob store's `clear()` path. The Rust layer owns the directory
	 *  scan because it has the same artifact matching rule used by targeted
	 *  deletion and transcription lookup.
	 */
	clearRecordingArtifacts: () =>
		typedError<number, RecorderError>(
			__TAURI_INVOKE('clear_recording_artifacts'),
		),
	/**
	 *  Canonical transcribe-by-id path. Resolves the audio file under
	 *  `<appDataDir>/recordings/{recordingId}.*` (cpal-written WAV,
	 *  navigator-saved webm/opus/mp4, etc.), decodes, then runs inference using
	 *  the per-call transcription spec supplied by the frontend.
	 */
	transcribeRecording: (recordingId: string, spec: TranscriptionSpec) =>
		typedError<string, TranscriptionError>(
			__TAURI_INVOKE('transcribe_recording', { recordingId, spec }),
		),
	/**
	 *  Prewarm the local model for `spec` so a following transcribe finds it
	 *  warm. The frontend fires this fire-and-forget at capture start (manual
	 *  record or VAD listen) for a local provider, overlapping the ~1 s model
	 *  load with the user's speech instead of paying it after they stop.
	 *
	 *  Idempotent and cheap: a no-op when the exact model is already resident.
	 *  Shares the one load path with `transcribe_recording` (`ModelCache::prewarm`
	 *  and `transcribe` both resolve through `ensure_engine_loaded`), so the model
	 *  warmed here is exactly the one transcribe will use, and a mid-recording
	 *  model change simply reloads at transcribe time. A failure here is
	 *  non-fatal: transcribe will load normally and surface any real error then.
	 */
	prewarmModel: (spec: TranscriptionSpec) =>
		typedError<null, TranscriptionError>(
			__TAURI_INVOKE('prewarm_model', { spec }),
		),
	/**
	 *  Open macOS Accessibility settings.
	 *
	 *  This is intentionally a fixed command instead of a general command
	 *  runner. The app only needs this one OS handoff, so the frontend should
	 *  not receive shell or process execution privileges.
	 */
	openAccessibilitySettings: () =>
		typedError<null, string>(__TAURI_INVOKE('open_accessibility_settings')),
	/**
	 *  Show the macOS Accessibility permission prompt.
	 *
	 *  macOS never lets an app grant itself Accessibility, so this only surfaces the
	 *  system prompt (which also adds the app to the Accessibility list, toggled
	 *  off); the live grant is observed by the Rust tap supervisor, not returned
	 *  here. Off macOS there is no such prompt, so this does nothing. Pairs with
	 *  `open_accessibility_settings` the way `request_microphone_permission` does
	 *  with the microphone privacy page.
	 */
	requestAccessibilityPermission: () =>
		__TAURI_INVOKE<void>('request_accessibility_permission'),
	/**
	 *  Read the microphone authorization the OS records up front.
	 *
	 *  One owner for every platform. macOS answers through
	 *  `tauri-plugin-macos-permissions` (AVFoundation), which reports a definitive
	 *  authorized-or-not, so macOS only ever reads `Granted` or `Denied` (a
	 *  not-yet-determined status reads as `Denied` and is resolved by the prompt in
	 *  `request_microphone_permission`). Windows reads the CapabilityAccessManager
	 *  ConsentStore. Every other platform (Linux) returns `Unknown`, where there is
	 *  no such store and the stream-open fallback stays the sole classifier.
	 */
	getMicrophonePermission: () =>
		__TAURI_INVOKE<MicrophonePermission>('get_microphone_permission'),
	/**
	 *  Elicit a microphone grant the way each platform allows, then let the caller
	 *  re-read `get_microphone_permission`.
	 *
	 *  macOS shows the system permission prompt (its only programmatic grant path).
	 *  Windows has no programmatic grant for an unpackaged desktop app, so when the
	 *  consent store reads `Denied` it deep-links the privacy page for the user to
	 *  toggle; an `Unknown`/`Granted` reading needs no nudge. Other platforms (Linux)
	 *  have no such affordance and do nothing.
	 */
	requestMicrophonePermission: () =>
		typedError<null, string>(__TAURI_INVOKE('request_microphone_permission')),
	/**
	 *  Reconcile the current local-model unload policy into the native idle
	 *  watcher. The frontend owns the value and pushes it on every change; Rust
	 *  owns the clock. Unlike the old ambient config, it carries no model
	 *  identity, so it applies whether or not a model is selected.
	 */
	setUnloadPolicy: (policy: UnloadPolicy) =>
		__TAURI_INVOKE<void>('set_unload_policy', { policy }),
	/**
	 *  Snapshot the current model state. Used by late-mounted observers (a
	 *  second window, the settings panel re-opening, etc.) to catch up to
	 *  the current lifecycle state without waiting for the next event on
	 *  `transcription://model-state`.
	 *
	 *  Reads the status plus resident model identity, if any.
	 */
	getTranscriptionState: () =>
		__TAURI_INVOKE<LocalModelState>('get_transcription_state'),
	/**
	 *  Link a file or directory already on disk into the engine's models folder as
	 *  `entry_name`. Validates the name and the source's engine shape strictly,
	 *  then symlinks. Replaces a stale link of the same name; refuses to clobber a
	 *  real (app-managed) entry. The frontend stores `entry_name` as the selection
	 *  just like a downloaded model.
	 */
	linkLocalModel: (engine: Engine, entryName: string, sourcePath: string) =>
		typedError<null, ModelImportError>(
			__TAURI_INVOKE('link_local_model', { engine, entryName, sourcePath }),
		),
	/**
	 *  List every selectable entry in the engine's models folder: model files
	 *  (.bin/.gguf/.ggml) for Whisper, directories for Parakeet and Moonshine, plus
	 *  symlinks to either. Hidden entries and in-flight `.partial` staging are
	 *  skipped. Returns an empty list when the folder does not exist yet.
	 */
	listModelEntries: (engine: Engine) =>
		typedError<ModelEntry[], ModelFolderError>(
			__TAURI_INVOKE('list_model_entries', { engine }),
		),
	/**
	 *  Remove one entry from the engine's models folder. A symlinked entry removes
	 *  only the link, never its target; a real entry is removed outright. The name
	 *  must be a single folder entry, so this can never reach outside the folder.
	 *  Succeeds when the entry is already gone.
	 */
	deleteModelEntry: (engine: Engine, name: string) =>
		typedError<null, ModelFolderError>(
			__TAURI_INVOKE('delete_model_entry', { engine, name }),
		),
	/**
	 *  Resolve an entry **through any symlink** and report each expected file's size
	 *  and completeness verdict. The webview passes the expected catalog sizes (it
	 *  owns the catalog); the 90% completeness rule lives here next to the stat, so
	 *  "what counts as a complete file on disk" has one owner shared with the
	 *  download integrity check (`is_size_complete`). An empty `filenames` means the
	 *  entry is itself the file (Whisper) and returns one element checked against
	 *  `expected_sizes[0]`; otherwise one element per filename (directory engines),
	 *  each checked against the aligned `expected_sizes`. A dead link reports
	 *  `size: None, complete: false`, so a linked-but-broken model reads as not
	 *  installed.
	 */
	resolveModelFiles: (
		engine: Engine,
		name: string,
		filenames: string[],
		expectedSizes: (number | null)[],
	) =>
		typedError<ModelFileStatus[], ModelFolderError>(
			__TAURI_INVOKE('resolve_model_files', {
				engine,
				name,
				filenames,
				expectedSizes,
			}),
		),
	/**
	 *  Download a model into its engine folder, cancelable via
	 *  `cancel_download(download_id)`. Stages under `{entry}.partial`, streams each
	 *  file, integrity-checks it against the passed catalog size, then promotes the
	 *  staging to the canonical path with one rename. A cancel (or any error)
	 *  removes the staging via a `Drop` guard, so an interrupted run never leaves a
	 *  partial install for the selector to list. Reports cumulative progress
	 *  (bytes so far / grand total) on `on_progress`.
	 */
	downloadModel: (
		engine: Engine,
		entryName: string,
		files: ModelFileDownload[],
		downloadId: string,
		onProgress: Channel<DownloadProgress>,
	) =>
		typedError<null, ModelFolderError>(
			__TAURI_INVOKE('download_model', {
				engine,
				entryName,
				files,
				downloadId,
				onProgress,
			}),
		),
	/**
	 *  Create the engine's models folder if needed and open it in the OS file
	 *  manager, so the user can drop in or remove models by hand.
	 */
	revealModelsFolder: (engine: Engine) =>
		typedError<null, ModelFolderError>(
			__TAURI_INVOKE('reveal_models_folder', { engine }),
		),
	/**
	 *  Abort the in-flight download registered under `download_id`, if any. The
	 *  matching `download_model` call then resolves with an `Err` (and its staging
	 *  is cleaned up by the dropped task). A no-op when nothing is downloading under
	 *  that id, so it is always safe to call.
	 */
	cancelDownload: (downloadId: string) =>
		__TAURI_INVOKE<void>('cancel_download', { downloadId }),
	/**
	 *  Pause every system media session currently playing. Returns one opaque token
	 *  per session paused, to hand back to `resume_playback`. Pausing is gated to
	 *  never *start* playback: only sessions observed playing are touched, and the
	 *  dedicated pause command (never a play/pause toggle) is sent.
	 */
	pausePlayback: () => __TAURI_INVOKE<string[]>('pause_playback'),
	/**
	 *  Resume the sessions named by `sessions`, which must be tokens returned by a
	 *  prior `pause_playback`. A session that vanished, was already resumed by the
	 *  user, or can't be resumed is silently skipped. Safety rule: we only ever send
	 *  *play* to a session we personally paused.
	 */
	resumePlayback: (sessions: string[]) =>
		__TAURI_INVOKE<void>('resume_playback', { sessions }),
	/**
	 *  Replace the full set of registered global shortcuts. The FE computes the
	 *  complete list from device-config and pushes it on startup and on every
	 *  change; the controller swaps its binding set atomically. Replace-all (not
	 *  per-command register/unregister) keeps the FE the single source of truth for
	 *  what is bound, with no add/remove bookkeeping to drift.
	 */
	setKeyboardShortcuts: (bindings: CommandBinding[]) =>
		__TAURI_INVOKE<void>('set_keyboard_shortcuts', { bindings }),
	/**
	 *  Tell the keyboard supervisor whether auto-paste-at-cursor is enabled. Paste
	 *  writes a synthetic Cmd/Ctrl+V through the same macOS Accessibility grant the
	 *  tap reads through, so the supervisor holds the tap whenever paste is on (even
	 *  with no binding) to track that grant and surface the notice when it is
	 *  missing. The FE pushes this on startup and whenever the output settings change.
	 */
	setAutoPasteEnabled: (enabled: boolean) =>
		__TAURI_INVOKE<void>('set_auto_paste_enabled', { enabled }),
	/**
	 *  Enter or leave binding-capture mode for the settings recorder. While
	 *  capturing, the tap emits the held combo as a `ShortcutCaptureEvent`
	 *  (which the recorder accumulates) instead of firing command triggers, so the
	 *  user can record Fn and physical-key bindings the webview cannot see.
	 */
	setKeyboardCapturing: (capturing: boolean) =>
		__TAURI_INVOKE<void>('set_keyboard_capturing', { capturing }),
	/**
	 *  The current dictation capability: whether Whispering can tap the keyboard for
	 *  global shortcuts and paste back. The FE seeds from this on attach, then
	 *  tracks `DictationCapabilityEvent` for changes; it never probes the OS itself.
	 *  The Rust supervisor owns the value and the tap's lifecycle, so there is no
	 *  `start` command for the FE to call.
	 */
	getDictationCapability: () =>
		__TAURI_INVOKE<DictationCapability>('get_dictation_capability'),
};

/** Events */
export const events = {
	dictationCapabilityEvent: makeEvent<DictationCapabilityEvent>(
		'dictation-capability-event',
	),
	modelStateEvent: makeEvent<ModelStateEvent>('model-state-event'),
	shortcutCaptureEvent: makeEvent<ShortcutCaptureEvent>(
		'shortcut-capture-event',
	),
	shortcutTriggerEvent: makeEvent<ShortcutTriggerEvent>(
		'shortcut-trigger-event',
	),
};

/* Types */
/**
 *  One command's binding, as sent from the FE registrar. `command_id` is the
 *  id the trigger event is emitted under; the FE filters by that command's `on`
 *  array and dispatches the callback.
 */
export type CommandBinding = {
	commandId: string;
	binding: KeyBinding;
};

/**
 *  The single source of truth for whether Whispering can drive its headline
 *  "dictate anywhere" flow: tap the keyboard for global shortcuts and paste a
 *  transcript back. macOS gates that on Accessibility trust, and the only
 *  process that can authoritatively know it is the one holding the rdev tap
 *  (this one), so Rust owns this value and the frontend is a pure view over it.
 *
 *  It folds two facts the frontend used to infer separately: the macOS trust
 *  probe (`AXIsProcessTrusted`) and the tap's liveness. Crucially `Broken` is
 *  distinguishable from `Active` only here, because `AXIsProcessTrusted` reports
 *  a stale post-update grant as trusted: the tap dying under a held grant is the
 *  only signal that tells them apart.
 */
export type DictationCapability =
	/**
	 *  The supervisor has not determined the value yet. Rust resolves this
	 *  synchronously at startup, so it exists only as the frontend's pre-seed
	 *  initial value before the first probe lands.
	 */
	| 'unknown'
	/**
	 *  This platform can never tap the keyboard (Linux Wayland: `rdev::listen`
	 *  receives no events). Terminal for the session.
	 */
	| 'unsupported'
	/**
	 *  No bound shortcut needs the tap (no Fn or modifier-only binding), so it is
	 *  deliberately not running and no Accessibility is touched. This is the
	 *  permission-free floor: chords go through the global-shortcut plugin and
	 *  the tap stays dormant until the user opts into a binding that needs it.
	 */
	| 'inactive'
	/**
	 *  macOS Accessibility is not granted. The tap is not running; turning
	 *  Whispering on in System Settings unlocks it.
	 */
	| 'untrusted'
	/**  The tap is running and (on macOS) the app is trusted. Dictation works. */
	| 'active'
	/**
	 *  macOS reports the app trusted, but the tap keeps dying under the held
	 *  grant: a stale post-update signature. Removing and re-adding Whispering
	 *  in Accessibility is the fix, which `Untrusted`'s "just toggle on" is not.
	 */
	| 'broken';

/**
 *  Pushed whenever the dictation capability changes. The frontend seeds from
 *  `get_dictation_capability` on attach, then tracks this event for transitions;
 *  it never probes the OS itself. A `tauri_specta::Event`, emitted with
 *  `emit_to(app, MAIN_WINDOW)` (the main webview, not the overlay) and listened
 *  through the generated `events.dictationCapabilityEvent`.
 */
export type DictationCapabilityEvent = {
	capability: DictationCapability;
};

/**
 *  Cumulative download progress for one model: bytes received so far across all
 *  of its files, and the grand total to expect. The frontend turns it into a
 *  0-100 percent.
 */
export type DownloadProgress = {
	/**
	 *  Bytes received so far. `f64` because specta forbids exporting 64-bit
	 *  ints to TypeScript; model sizes are far below `f64`'s 2^53 exact-integer
	 *  ceiling, so no precision is lost.
	 */
	bytesReceived: number | null;
	/**  Grand total bytes for the whole model (sum of the catalog file sizes). */
	totalBytes: number | null;
};

/**
 *  Local transcription engine. Wire tags match the frontend
 *  `transcription.service` enum (`whispercpp` / `parakeet` / `moonshine`).
 */
export type Engine = 'whispercpp' | 'parakeet' | 'moonshine';

/**
 *  A non-modifier key, named by physical position (Wave 1 Lock: desktop binds
 *  in physical-key space, not produced-character space). Variant names mirror
 *  rdev's `Key` for the keys we support so the rdev mapping is near 1:1, but
 *  this is our own stable enum: the persisted binding format must not depend on
 *  rdev's enum names. Keys outside this set are not bindable (`rdev_map` returns
 *  `None`), which keeps this a pure string union on the TypeScript side.
 */
export type Key =
	| 'keyA'
	| 'keyB'
	| 'keyC'
	| 'keyD'
	| 'keyE'
	| 'keyF'
	| 'keyG'
	| 'keyH'
	| 'keyI'
	| 'keyJ'
	| 'keyK'
	| 'keyL'
	| 'keyM'
	| 'keyN'
	| 'keyO'
	| 'keyP'
	| 'keyQ'
	| 'keyR'
	| 'keyS'
	| 'keyT'
	| 'keyU'
	| 'keyV'
	| 'keyW'
	| 'keyX'
	| 'keyY'
	| 'keyZ'
	| 'num0'
	| 'num1'
	| 'num2'
	| 'num3'
	| 'num4'
	| 'num5'
	| 'num6'
	| 'num7'
	| 'num8'
	| 'num9'
	| 'f1'
	| 'f2'
	| 'f3'
	| 'f4'
	| 'f5'
	| 'f6'
	| 'f7'
	| 'f8'
	| 'f9'
	| 'f10'
	| 'f11'
	| 'f12'
	| 'f13'
	| 'f14'
	| 'f15'
	| 'f16'
	| 'f17'
	| 'f18'
	| 'f19'
	| 'f20'
	| 'f21'
	| 'f22'
	| 'f23'
	| 'f24'
	| 'space'
	| 'return'
	| 'tab'
	| 'escape'
	| 'backspace'
	| 'delete'
	| 'insert'
	| 'upArrow'
	| 'downArrow'
	| 'leftArrow'
	| 'rightArrow'
	| 'home'
	| 'end'
	| 'pageUp'
	| 'pageDown'
	| 'minus'
	| 'equal'
	| 'leftBracket'
	| 'rightBracket'
	| 'semiColon'
	| 'quote'
	| 'backQuote'
	| 'backSlash'
	| 'comma'
	| 'dot'
	| 'slash';

/**
 *  A desktop global binding. It fires when its modifiers and keys are held
 *  exactly (see `Matcher`), matching the existing `arraysMatch` semantics of
 *  `local-shortcut-manager` and the plugin's exact-modifier behavior. An empty
 *  `keys` with non-empty `modifiers` is a modifier-only hold (for example hold
 *  Meta), which was impossible with the plugin. The matcher also accepts a bare
 *  key with no modifiers, but the frontend refuses to *configure* one (a global
 *  gesture must carry a modifier or Fn so it cannot fire on an ordinary
 *  keypress); the matcher stays permissive so the policy lives in one place.
 */
export type KeyBinding = {
	modifiers: Modifier[];
	keys: Key[];
};

/**
 *  Snapshot of everything observable about the resident model. Every event
 *  carries a full snapshot rather than a delta because `AppHandle::emit`
 *  does not replay to future windows: a window opened mid-load reads the
 *  current snapshot via `get_transcription_state` and then catches up via
 *  the next event.
 */
export type LocalModelState = {
	engine: Engine | null;
	/**
	 *  Entry name inside the engine's models directory, mirroring
	 *  `TranscriptionSpec::model_name`.
	 */
	modelName: string | null;
	status: ModelStatus;
};

/**
 *  The OS-level microphone authorization, read from the platform privacy store.
 *
 *  Only an explicit `Denied` gates recording. `Unknown` (no entry in the store,
 *  or a platform with no such gate) means "can't tell from here": the caller
 *  treats it as available and lets the recorder's stream-open fallback
 *  (`recorder::error::classify_cpal`) classify any real denial from the error
 *  itself. So this signal can only *add* a pre-record denial; it never newly
 *  blocks a setup that was already working.
 */
export type MicrophonePermission = 'granted' | 'denied' | 'unknown';

/**  One selectable entry in an engine's models folder. */
export type ModelEntry = {
	/**  File or directory name inside the engine's models folder. */
	name: string;
	/**
	 *  Whether the entry is a symlink (a "bring your own model" link). Display
	 *  only ("Your model (linked)"); it does not change how the entry loads.
	 */
	linked: boolean;
};

/**
 *  One file to download for a model. Mirrors the catalog shape: a Whisper model
 *  passes a single file, a directory engine passes one per contained file.
 */
export type ModelFileDownload = {
	url: string;
	/**
	 *  Filename inside the entry directory (directory engines). Ignored for the
	 *  single-file Whisper case, where the entry itself is the file.
	 */
	filename: string;
	/**  Catalog size in bytes; the integrity check and progress total use it. */
	sizeBytes: number | null;
};

/**
 *  One file's presence and completeness in a model entry, resolved through any
 *  symlink. The webview supplies expected catalog sizes and reads back both the
 *  stat'd `size` (for messaging) and the `complete` verdict (for installed /
 *  truncated decisions). The completeness rule itself lives in Rust; see
 *  `is_size_complete`.
 */
export type ModelFileStatus = {
	/**
	 *  File size in bytes, following symlinks. `None` when missing or unreadable
	 *  (a dead link whose target is gone, or a file never created).
	 */
	size: number | null;
	/**
	 *  Whether the file is present and at least the completeness floor (90%) of
	 *  its expected catalog size. A missing file is never complete.
	 */
	complete: boolean;
};

export type ModelFolderError =
	/**  The entry name (or a download filename) is not a single folder entry. */
	| { name: 'InvalidEntryName'; message: string }
	/**  Could not read the models folder or resolve its path. */
	| { name: 'ReadFailed'; message: string }
	/**  Removing the entry failed. */
	| { name: 'DeleteFailed'; message: string }
	/**
	 *  A download finished smaller than its catalog size (a dropped connection
	 *  leaves a truncated file that still "loads" but transcribes garbage).
	 */
	| { name: 'DownloadIncomplete'; message: string }
	/**  A download failed or was cancelled (an aborted transfer surfaces here). */
	| { name: 'DownloadFailed'; message: string }
	/**  Could not create or open the models folder. */
	| { name: 'RevealFailed'; message: string };

export type ModelImportError =
	/**
	 *  The chosen registry entry name is not a single folder entry, or (for
	 *  Moonshine) does not match the `moonshine-{variant}-{lang}` convention.
	 */
	| { name: 'InvalidEntryName'; message: string }
	/**
	 *  A real, app-managed model with the chosen name already occupies the
	 *  folder. Refused rather than clobbered so linking never deletes
	 *  downloaded bytes. Carries the colliding name (`entry`, not `name`, which
	 *  is the serde discriminant) so the UI can guide the user to delete that
	 *  existing entry first.
	 */
	| { name: 'EntryExists'; entry: string }
	/**
	 *  The picked file/directory does not have the exact shape the engine's
	 *  loader needs.
	 */
	| { name: 'IncompatibleModel'; message: string }
	/**  Creating (or replacing) the symlink failed. */
	| { name: 'LinkFailed'; message: string };

/**
 *  Single event type for everything observable about the model lifecycle.
 *  `tag = "kind"` matches `ModelStatus` and `UnloadReason` so the FE pattern
 *  is uniform: `switch (event.kind)`.
 *
 *  Registered as a `tauri_specta::Event`, so the Rust emitter
 *  (`event.emit(&app)`) and the generated FE binding (`events.modelStateEvent`)
 *  share one generated topic name instead of a hand-mirrored string.
 */
export type ModelStateEvent =
	| { kind: 'loading_started'; state: LocalModelState }
	| { kind: 'loading_completed'; state: LocalModelState; elapsedMs: number }
	| { kind: 'loading_failed'; state: LocalModelState; error: string }
	| { kind: 'inference_started'; state: LocalModelState }
	| { kind: 'inference_completed'; state: LocalModelState; elapsedMs: number }
	| { kind: 'inference_failed'; state: LocalModelState; error: string }
	| { kind: 'unloaded'; state: LocalModelState; reason: UnloadReason };

/**
 *  Lifecycle state of the resident model. Owned by an `Arc<RwLock<...>>`
 *  inside `ModelCache` so `snapshot()` can read it without touching the
 *  cache mutex (which is held across long-running inference).
 */
export type ModelStatus =
	/**
	 *  No model resident and none loading. Initial state, and reached after
	 *  `Unloaded`.
	 */
	| { kind: 'idle' }
	/**  `with_engine` is currently inside the `load(&model_path)` call. */
	| { kind: 'loading' }
	/**  A model is resident and not currently in use. */
	| { kind: 'ready' }
	/**
	 *  `with_engine` is currently inside the user closure (transcribe call).
	 *  The cache lock is held; `snapshot()` reports this without contending.
	 */
	| { kind: 'inferring' }
	/**
	 *  The last attempt to load or transcribe failed. Inference failures may
	 *  leave the engine resident so a later transcription can reuse it.
	 */
	| { kind: 'error'; message: string };

/**
 *  A logical modifier. Left and right are collapsed in v1 (ControlLeft and
 *  ControlRight both become `Ctrl`); the Wayland and left/right gaps are
 *  documented refusals in the spec. `Fn` is the capability the Tauri
 *  global-shortcut plugin could never express.
 */
export type Modifier = 'ctrl' | 'alt' | 'shift' | 'meta' | 'fn';

export type RecorderError =
	/**
	 *  The OS refused microphone access. The frontend checks microphone
	 *  permission before recording, so this is the stream-open fallback for a
	 *  denial that slips past that gate (e.g. a declined first-run prompt).
	 */
	| { name: 'PermissionDenied'; message: string }
	/**
	 *  No usable input device: none selected and no default, the named device
	 *  is gone, cpal reports the device unavailable mid-open, or the device
	 *  yields no input configurations at all (query errors or returns empty).
	 */
	| { name: 'NoInputDevice'; message: string }
	/**
	 *  Any other recording failure (device config, stream build, filesystem,
	 *  session lifecycle, internal). The frontend does not branch on these.
	 */
	| { name: 'Failed'; message: string };

/**
 *  Serializable handle returned to the JS side. The id is the lookup key
 *  for every later operation; the rest is metadata the UI needs without
 *  having to read the file (duration for analytics, byteLength for artifact
 *  diagnostics, mimeType for the player).
 *
 *  `mime_type` is `String` rather than `&'static str` so specta's TS
 *  generator sees a stable serializable shape. The runtime cost is one short
 *  allocation per artifact write.
 *
 *  `duration_ms` and `byte_length` use `#[specta(type = Number<u64>)]`
 *  to opt out of specta's bigint guard: both stay well under
 *  `Number.MAX_SAFE_INTEGER` (2^53) for any plausible recording
 *  (duration in ms maxes at ~285,000 years; byte length is bounded by
 *  the filesystem).
 */
export type RecordingArtifact = {
	id: string;
	durationMs: number;
	byteLength: number;
	mimeType: string;
};

/**
 *  Streamed on every change of the currently-held combo while the settings
 *  recorder is capturing a new binding. A dedicated event type (rather than
 *  emitting a bare `KeyBinding`) so capture is a `tauri_specta::Event` like the
 *  trigger, with a generated topic and FE binding. Recording goes through rdev,
 *  not the webview, because only rdev sees the Fn key and physical-key
 *  positions, so the captured binding is exactly what the matcher will later
 *  match. The FE accumulates these snapshots and commits when all keys release.
 */
export type ShortcutCaptureEvent = {
	binding: KeyBinding;
};

/**
 *  Emitted on every binding transition. `command_id` is the id the binding was
 *  registered under; the FE filters by that command's `on` array and dispatches
 *  the callback. Rust stays command-agnostic: it knows the id and the edge, not
 *  which states a given command cares about.
 *
 *  A `tauri_specta::Event`, so the listener emits it with
 *  `trigger.emit_to(app, MAIN_WINDOW)` (targeting the main webview, not the
 *  overlay) and the FE listens through the generated `events.shortcutTriggerEvent`.
 */
export type ShortcutTriggerEvent = {
	commandId: string;
	state: TriggerState;
};

export type TranscriptionError =
	| { name: 'AudioReadError'; message: string }
	| { name: 'GpuError'; message: string }
	| { name: 'ModelLoadError'; message: string }
	| { name: 'TranscriptionError'; message: string }
	/**
	 *  The per-call spec holds a value that cannot be dispatched (e.g. a
	 *  Moonshine model path that does not match `moonshine-{variant}-{lang}`).
	 */
	| { name: 'ConfigError'; message: string };

/**
 *  Per-call transcription inputs owned by the frontend. The Rust side receives
 *  this with `transcribe_recording`, resolves the model at point of use, and
 *  keeps only the resident model cache. Nothing here is retained between calls,
 *  so there is no ambient config to go stale.
 */
export type TranscriptionSpec = {
	engine: Engine;
	/**
	 *  Entry name inside the engine's models directory (a single file or
	 *  directory name, never a path). `ModelCache` resolves it under
	 *  `{app_data}/models/{engine}/` at load time, so a path never exists
	 *  as data anywhere in the system.
	 */
	modelName: string;
	language?: string | null;
	initialPrompt?: string | null;
};

/**
 *  Whether a binding just became fully held (`Pressed`) or stopped being fully
 *  held (`Released`). The variant names serialize verbatim to `"Pressed"` /
 *  `"Released"`, which is exactly the `ShortcutEventState` the Tauri
 *  global-shortcut plugin used to deliver, so the command layer (`commands.ts`)
 *  is unchanged: only the producer of these strings changes.
 */
export type TriggerState = 'Pressed' | 'Released';

/**
 *  How long after the last transcription the resident model should be
 *  dropped. Mirrors the frontend `transcription.localModelUnloadPolicy`
 *  device setting; serde tags below match its wire format exactly.
 *
 *  `Immediately` is enforced synchronously at the end of each transcription;
 *  timed variants are enforced by the background idle watcher.
 */
export type UnloadPolicy =
	| 'never'
	| 'immediately'
	| 'after_5_minutes'
	| 'after_30_minutes';

/**
 *  Reason the resident model was dropped. Folded into a single event variant
 *  (`ModelStateEvent::Unloaded`) rather than fanned out into per-reason
 *  variants so the FE has one branch to handle.
 */
export type UnloadReason =
	/**
	 *  Synchronous eviction after a transcription completed under the
	 *  `Immediately` unload policy.
	 */
	| { kind: 'immediate' }
	/**
	 *  Background idle watcher dropped the model after the configured timeout
	 *  elapsed without activity.
	 */
	| { kind: 'idle'; idleSecs: number };

/**
 *  Where `write_text` left the transcript.
 *
 *  - `Pasted`: a synthetic paste landed it at the cursor. When the caller asked
 *    to keep the transcript on the clipboard the transcript stays there;
 *    otherwise the clipboard is restored to whatever the user had (see
 *    `write_text`).
 *  - `LeftOnClipboard`: delivery could not paste (no Accessibility grant, or the
 *    paste itself failed), so the transcript was left on the clipboard as the
 *    fallback — always one ⌘V away.
 *
 *  The frontend maps this to the dictation pill's delivery reach.
 */
export type WriteTextOutcome = 'pasted' | 'leftOnClipboard';

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}

type EventEmit<T> = [T] extends [null]
	? () => Promise<void>
	: (payload: T) => Promise<void>;

function makeEvent<T>(
	name: string,
	serialize?: (payload: T) => unknown,
	deserialize?: (payload: any) => T,
) {
	const mapEvent =
		(cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
			cb({
				...event,
				payload: deserialize ? deserialize(event.payload) : event.payload,
			});
	const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

	const base = {
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			__TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	};

	const fn = (
		target:
			| import('@tauri-apps/api/webview').Webview
			| import('@tauri-apps/api/window').Window,
	) => ({
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	});

	return Object.assign(fn, base);
}
