//! Durable recording artifact: a 16 kHz mono IEEE-float WAV file written to
//! `<appDataDir>/recordings/{id}.wav`. This path matches the JS file-system
//! blob store (`PATHS.DB.RECORDING_AUDIO`) so history playback, deletion, and
//! the `convertFileSrc` URL flow work without an extra copy.
//!
//! JS never sees raw PCM samples on the wire. The IPC shape is the small
//! `RecordingArtifact` JSON handle returned by `stop_recording`; later
//! operations (transcribe, encode for upload, delete) take the id and look
//! the file up here.
//!
//! Rust owns the recordings directory: callers pass an id, never a path.
//! `validate_recording_id` rejects separators or traversal sequences
//! before they reach the filesystem.
//!
//! Reader-friendly callers should prefer the high-level functions in this
//! module over reaching for raw paths.

use std::collections::HashSet;
use std::fs::OpenOptions;
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

use serde::Serialize;
use tauri::{AppHandle, Manager};

use crate::audio::decode_to_pcm16k_mono;

/// Target rate for every cpal-written artifact. Matches the recorder's
/// finalize contract and the rate all local transcription engines want.
const ARTIFACT_RATE: u32 = 16_000;
const ARTIFACT_CHANNELS: u16 = 1;

/// File extension Rust writes for cpal artifacts. Other producers
/// (navigator MediaRecorder via the JS blob store) may write other
/// extensions; `find_recording_path` resolves by id-prefix regardless.
const ARTIFACT_EXT: &str = "wav";
const ARTIFACT_MIME: &str = "audio/wav";

/// Subdirectory under the app data dir. Mirrors `PATHS.DB.RECORDINGS()` on
/// the JS side so the blob store keeps finding files by id prefix.
const RECORDINGS_DIR_NAME: &str = "recordings";

/// Serializable handle returned to the JS side. The id is the lookup key
/// for every later operation; the rest is metadata the UI needs without
/// having to read the file (duration for analytics, byteLength for artifact
/// diagnostics, mimeType for the player).
///
/// `mime_type` is `String` rather than `&'static str` so specta's TS
/// generator sees a stable serializable shape. The runtime cost is one short
/// allocation per artifact write.
///
/// `duration_ms` and `byte_length` use `#[specta(type = Number<u64>)]`
/// to opt out of specta's bigint guard: both stay well under
/// `Number.MAX_SAFE_INTEGER` (2^53) for any plausible recording
/// (duration in ms maxes at ~285,000 years; byte length is bounded by
/// the filesystem).
#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RecordingArtifact {
    pub id: String,
    #[specta(type = specta_typescript::Number<u64>)]
    pub duration_ms: u64,
    #[specta(type = specta_typescript::Number<u64>)]
    pub byte_length: u64,
    pub mime_type: String,
}

/// Validate that `id` is a single safe filename component: no separators,
/// no traversal, no embedded NULs. We don't constrain the alphabet beyond
/// "no path tricks" because ids are generated by nanoid in JS and we trust
/// that source, but a malicious caller cannot use an id to escape the
/// recordings directory.
fn validate_recording_id(id: &str) -> Result<(), String> {
    if id.is_empty() {
        return Err("recording id is empty".to_string());
    }
    if id.len() > 128 {
        return Err(format!("recording id is too long ({} chars)", id.len()));
    }
    if id.contains('/')
        || id.contains('\\')
        || id.contains('\0')
        || id == "."
        || id == ".."
        || id.contains("..")
    {
        return Err(format!(
            "recording id '{id}' contains path separators or traversal"
        ));
    }
    Ok(())
}

/// Resolve the directory that holds all recording artifacts. Created on
/// demand on the first write; readers expect it to exist.
pub(crate) fn recordings_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let app_data = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("resolve app data dir: {e}"))?;
    Ok(app_data.join(RECORDINGS_DIR_NAME))
}

/// Resolve the write path for a new cpal artifact. The cpal writer always
/// produces `.wav`; reads use `find_recording_path` which accepts any
/// extension (so navigator/file-upload blobs saved by JS still resolve).
fn recording_path(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    validate_recording_id(id)?;
    Ok(recordings_dir(app)?.join(format!("{id}.{ARTIFACT_EXT}")))
}

/// Resolve the file path for an existing recording id, regardless of
/// extension. Mirrors the JS blob store's `findAudioFile`: scan the
/// recordings dir for `{id}.*` and return the first non-metadata match.
///
/// Returns an error if no audio file exists. Callers should map that to
/// a user-facing "recording not found" message.
fn find_recording_path(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    validate_recording_id(id)?;
    let dir = recordings_dir(app)?;
    let entries = std::fs::read_dir(&dir)
        .map_err(|e| format!("read recordings dir {}: {e}", dir.display()))?;
    let prefix = format!("{id}.");
    for entry in entries {
        let entry = entry.map_err(|e| format!("read recordings dir {}: {e}", dir.display()))?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with(&prefix) && is_recording_artifact_name(&name) {
            return Ok(entry.path());
        }
    }
    Err(format!("no recording artifact found for id '{id}'"))
}

fn is_recording_artifact_name(name: &str) -> bool {
    !name.ends_with(".md")
}

fn recording_id_from_artifact_filename(name: &str) -> Option<&str> {
    if !is_recording_artifact_name(name) {
        return None;
    }
    Some(name.split_once('.').map_or(name, |(id, _)| id))
}

fn remove_file_if_present(path: &Path) -> Result<bool, String> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(true),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(format!("delete artifact {}: {e}", path.display())),
    }
}

fn delete_recording_artifacts_matching(
    app: &AppHandle,
    mut matches: impl FnMut(&str) -> bool,
) -> Result<u32, String> {
    let dir = recordings_dir(app)?;
    let entries = match std::fs::read_dir(&dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(0),
        Err(e) => return Err(format!("read recordings dir {}: {e}", dir.display())),
    };

    let mut deleted = 0;
    for entry in entries {
        let entry = entry.map_err(|e| format!("read recordings dir {}: {e}", dir.display()))?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if !matches(&name) {
            continue;
        }

        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|e| format!("stat artifact {}: {e}", path.display()))?;
        if file_type.is_file() && remove_file_if_present(&path)? {
            deleted += 1;
        }
    }

    Ok(deleted)
}

/// Synthesize and write a mono 16 kHz IEEE-float WAV from in-memory PCM
/// samples. Returns the artifact handle. The caller is responsible for
/// passing samples that are already at `ARTIFACT_RATE` (the recorder
/// consumer worker resamples at finalize, so this holds for cpal callers).
pub fn write_artifact(
    app: &AppHandle,
    id: &str,
    samples: &[f32],
) -> Result<RecordingArtifact, String> {
    let path = recording_path(app, id)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create recordings dir {}: {e}", parent.display()))?;
    }

    write_pcm_as_wav(&path, samples)?;

    let byte_length = std::fs::metadata(&path)
        .map_err(|e| format!("stat artifact {}: {e}", path.display()))?
        .len();

    let duration_ms = (samples.len() as f64 / ARTIFACT_RATE as f64 * 1000.0).round() as u64;

    Ok(RecordingArtifact {
        id: id.to_string(),
        duration_ms,
        byte_length,
        mime_type: ARTIFACT_MIME.to_string(),
    })
}

/// Read and decode an artifact to 16 kHz mono f32 PCM. Shared by the
/// transcribe-from-recording-id path and the cloud-upload re-encode path.
/// Accepts any container Symphonia can decode (cpal-written WAV,
/// navigator-saved webm/opus/mp4, etc.).
pub fn read_artifact_samples(app: &AppHandle, id: &str) -> Result<Vec<f32>, String> {
    let path = find_recording_path(app, id)?;
    let bytes =
        std::fs::read(&path).map_err(|e| format!("read artifact {}: {e}", path.display()))?;
    decode_to_pcm16k_mono(&bytes).map_err(|e| format!("decode artifact {}: {e}", path.display()))
}

/// Delete recording artifacts by recording id.
///
/// Artifact matching lives here instead of in TypeScript so the front end
/// never gets a generic "delete files in this directory" primitive. Missing
/// files are not an error, which lets callers retry after partial cleanup.
pub(super) fn delete_artifacts(app: &AppHandle, ids: &[String]) -> Result<u32, String> {
    let mut target_ids = HashSet::with_capacity(ids.len());
    for id in ids {
        validate_recording_id(id)?;
        target_ids.insert(id.as_str());
    }

    if target_ids.is_empty() {
        return Ok(0);
    }

    delete_recording_artifacts_matching(app, |name| {
        recording_id_from_artifact_filename(name).is_some_and(|id| target_ids.contains(id))
    })
}

/// Delete every recording artifact while leaving exported markdown sidecars.
///
/// The recordings directory may contain `{id}.md` files owned by the markdown
/// exporter. Those are metadata sidecars, not blobs, so bulk audio cleanup
/// must leave them alone.
pub(super) fn clear_artifacts(app: &AppHandle) -> Result<u32, String> {
    delete_recording_artifacts_matching(app, is_recording_artifact_name)
}

/// Write a mono 16 kHz IEEE-float WAV directly. The header is small and
/// stable enough to hand-write here rather than route through `hound`,
/// which has a less ergonomic API for the recovered-writer-then-sync_all
/// flow we want. The file is fsynced before returning so the artifact
/// handle never points at a partially flushed file.
fn write_pcm_as_wav(path: &Path, samples: &[f32]) -> Result<(), String> {
    let bits_per_sample: u16 = 32;
    let bytes_per_sample: u32 = (bits_per_sample / 8) as u32;
    let channels = ARTIFACT_CHANNELS;
    let rate = ARTIFACT_RATE;
    let data_size: u32 = (samples.len() as u32)
        .checked_mul(bytes_per_sample)
        .ok_or_else(|| "wav data size overflow".to_string())?;
    let file_size: u32 = 36u32
        .checked_add(data_size)
        .ok_or_else(|| "wav file size overflow".to_string())?;

    let file = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .open(path)
        .map_err(|e| format!("open artifact {}: {e}", path.display()))?;
    let mut w = BufWriter::new(file);

    // RIFF header
    w.write_all(b"RIFF").map_err(io_err(path))?;
    w.write_all(&file_size.to_le_bytes())
        .map_err(io_err(path))?;
    w.write_all(b"WAVE").map_err(io_err(path))?;
    // fmt chunk
    w.write_all(b"fmt ").map_err(io_err(path))?;
    w.write_all(&16u32.to_le_bytes()).map_err(io_err(path))?;
    // Format tag 3 = IEEE float (per the WAVE spec, the original PCM tag 1
    // is for integer samples; tag 3 indicates IEEE 754 float samples).
    w.write_all(&3u16.to_le_bytes()).map_err(io_err(path))?;
    w.write_all(&channels.to_le_bytes()).map_err(io_err(path))?;
    w.write_all(&rate.to_le_bytes()).map_err(io_err(path))?;
    let byte_rate: u32 = rate * channels as u32 * bytes_per_sample;
    w.write_all(&byte_rate.to_le_bytes())
        .map_err(io_err(path))?;
    let block_align: u16 = channels * bytes_per_sample as u16;
    w.write_all(&block_align.to_le_bytes())
        .map_err(io_err(path))?;
    w.write_all(&bits_per_sample.to_le_bytes())
        .map_err(io_err(path))?;
    // data chunk
    w.write_all(b"data").map_err(io_err(path))?;
    w.write_all(&data_size.to_le_bytes())
        .map_err(io_err(path))?;
    for &s in samples {
        w.write_all(&s.to_le_bytes()).map_err(io_err(path))?;
    }

    let file = w
        .into_inner()
        .map_err(|e| format!("flush wav {}: {e}", path.display()))?;
    file.sync_all()
        .map_err(|e| format!("sync wav {}: {e}", path.display()))?;
    Ok(())
}

fn io_err(path: &Path) -> impl Fn(std::io::Error) -> String + '_ {
    move |e: std::io::Error| format!("write wav {}: {e}", path.display())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_rejects_traversal() {
        assert!(validate_recording_id("../escape").is_err());
        assert!(validate_recording_id("a/b").is_err());
        assert!(validate_recording_id("a\\b").is_err());
        assert!(validate_recording_id("..").is_err());
        assert!(validate_recording_id(".").is_err());
        assert!(validate_recording_id("a\0b").is_err());
        assert!(validate_recording_id("").is_err());
    }

    #[test]
    fn validate_accepts_nanoid_shapes() {
        assert!(validate_recording_id("abc123").is_ok());
        assert!(validate_recording_id("V1StGXR8_Z5jdHi6B-myT").is_ok());
        assert!(validate_recording_id("rec_2026-05-26T12-34-56").is_ok());
    }

    #[test]
    fn artifact_filename_matching_ignores_markdown_sidecars() {
        assert_eq!(recording_id_from_artifact_filename("abc.wav"), Some("abc"));
        assert_eq!(recording_id_from_artifact_filename("abc.webm"), Some("abc"));
        assert_eq!(recording_id_from_artifact_filename("abc.md"), None);
    }

    /// Measures the file round-trip the live path pays today: WAV write + fsync,
    /// then read + Symphonia decode. This is the "removable" quantity in the
    /// spec's falsification benchmark, and the thing the parked handoff +
    /// async-persist optimization would take off the critical path. Not an
    /// assertion of speed (hardware varies); it asserts the round-trip is
    /// lossless and prints the numbers. Run with:
    ///
    /// ```sh
    /// cargo test -p whispering file_roundtrip_overhead -- --nocapture
    /// ```
    #[test]
    fn file_roundtrip_overhead() {
        use std::time::Instant;
        let dir = std::env::temp_dir();
        for &secs in &[5usize, 15, 60] {
            let n = secs * ARTIFACT_RATE as usize;
            // A quiet sine so the decode does real work on plausible samples.
            let samples: Vec<f32> = (0..n).map(|i| (i as f32 * 0.05).sin() * 0.25).collect();
            let path = dir.join(format!("whispering_roundtrip_{secs}s.wav"));

            let t0 = Instant::now();
            write_pcm_as_wav(&path, &samples).expect("write wav");
            let write_ms = t0.elapsed().as_secs_f64() * 1000.0;

            let t1 = Instant::now();
            let bytes = std::fs::read(&path).expect("read wav");
            let decoded = decode_to_pcm16k_mono(&bytes).expect("decode wav");
            let read_decode_ms = t1.elapsed().as_secs_f64() * 1000.0;

            assert_eq!(
                decoded.len(),
                samples.len(),
                "round-trip changed the sample count"
            );
            println!(
                "[roundtrip] {secs:>2}s ({n} samples): write+fsync {write_ms:6.2}ms  read+decode {read_decode_ms:6.2}ms  total {:6.2}ms",
                write_ms + read_decode_ms
            );
            let _ = std::fs::remove_file(&path);
        }
    }
}
